services:
  database:
    image: mysql:8.0
    container_name: service-database-mysql
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-ospsystem}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-R00tP@ssw0rd}
      MYSQL_USER: ${DB_USERNAME:-system_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-P@ssw0rd}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - service-network

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: service-phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USERNAME:-system_user}
      PMA_PASSWORD: ${DB_PASSWORD:-P@ssw0rd}
      UPLOAD_LIMIT: 300M
    depends_on:
      - database
    networks:
      - service-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: service-api-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./.env:/var/www/html/.env
    env_file:
      - ./.env
    environment:
      DB_HOST: database
    depends_on:
      - database
    networks:
      - service-network

  web-panel:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: service-web-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - service-network

networks:
  service-network:
    driver: bridge

volumes:
  db_data:
    driver: local
